Repository pulkit-30/Frontend-Animations, pull requests merged in 2021-10, with the labels that each got.

#26 Temp
  Double Click Heart/README.md
  Double Click Heart/index.html
  Double Click Heart/script.js
  Double Click Heart/style.css
  Valentines/HappyMonkey-Regular.ttf
  Valentines/Heart.js
  Valentines/HeartRain.js
  Valentines/README.md
  Valentines/index.html
  Valentines/index.js
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#27 Update Index.html and style.css file
  Double Click Heart/index.html
  Double Click Heart/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#28 Added confetti animation
  confetti-animation/demo.mp4
  confetti-animation/index.html
  confetti-animation/readme.md
  confetti-animation/script.js
  confetti-animation/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#31 added Particle brush
  Particle Brush/Particle.js
  Particle Brush/README.md
  Particle Brush/index.html
  Particle Brush/index.js
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#33 Bouncing Balls Animation
  Bouncing Balls/README.md
  Bouncing Balls/Screenshot (89).png
  Bouncing Balls/index.html
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#34 Add Continuous Integration workflows using GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#37 fix the background color for spring animation
  Spring Animation/Style.css
Labels: hactoberfest-accepted, hactoberfest2021, open-source, hacktoberfest2021, hacktoberfest-accepted

#36 fix : issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hactoberfest-accepted, hactoberfest2021, open-source, hacktoberfest2021, hacktoberfest-accepted

#38 Update index.html
  Valentines/index.html
Labels: hactoberfest-accepted, hactoberfest2021, open-source, hacktoberfest2021, hacktoberfest-accepted

#35 comets animation
  Comets Animation/README.md
  Comets Animation/comets.png
  Comets Animation/index.html
  Comets Animation/styles.css
  README.md
Labels: hactoberfest-accepted, hactoberfest2021, hacktoberfest2021, hacktoberfest-accepted

#40 Glowing-Dot-Animation
  Glowing Dot Animation/image.jpg
  Glowing Dot Animation/index.html
  Glowing Dot Animation/readme.md
  Glowing Dot Animation/style.css
  README.md
Labels: hactoberfest-accepted, hactoberfest2021, open-source, hacktoberfest2021, hacktoberfest-accepted

#41 Gradient Loader
  Neumorphism gradient loader/image.jpg
  Neumorphism gradient loader/index.html
  Neumorphism gradient loader/readme.md
  Neumorphism gradient loader/style.css
  README.md
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#88 At mcard
  ATM Card Input/Capture.PNG
  ATM Card Input/README.md
  ATM Card Input/animation.js
  ATM Card Input/index.html
  ATM Card Input/style.css
Labels: hacktoberfest2021, hacktoberfest-accepted, hacktoberfest
